# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kind-rb` gem.
# Please instead update this file by running `bin/tapioca gem kind-rb`.

# source://kind-rb//lib/kind-rb.rb#1
module KindRb
  class << self
    # source://kind-rb//lib/kind-rb.rb#2
    def executable; end
  end
end
