# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kubectl-rb` gem.
# Please instead update this file by running `bin/tapioca gem kubectl-rb`.

# source://kubectl-rb//lib/kubectl-rb.rb#1
module KubectlRb
  class << self
    # source://kubectl-rb//lib/kubectl-rb.rb#2
    def executable; end
  end
end
