name: Typecheck
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Generate RBIs
        run: rm -r sorbet/rbi/gems && bundle exec tapioca gem
      - name: Run Sorbet
        run: bundle exec srb tc
